### ISSUE TITLE
Corefactors Don't Always Show (BUG)

### ISSUE THREAD

**Issue by sridharkaza** [employmeo/employmeo#1]
After scoring, the corefactors don't always show up in the respondant score page - issue seems to be that the JPA cache is not refreshing the scores when the respondant is being refreshed

**Comment by nshah-employmeo** [comment]
Unable to reproduce issue.
Yet, provided mapping fix for eager fetch, cascade refresh to ensure desired behavior at this time. Confirmed children weren't loaded at all times with the respondant entity refresh earlier on, unless the children list was accessed (which would fetch the list lazily)
